### ISSUE TITLE
Current ArchLinuxARM-rpi-latest needs bsdtar 3.3+ (unavailable in Ubuntu)

### ISSUE THREAD

**Issue by cprima** [helotism/helotism#8]
@see https://archlinuxarm.org/forum/viewtopic.php?f=64&t=11396&start=10

wget https://www.libarchive.org/downloads/libarchive-3.3.1.tar.gz
tar xzf libarchive-3.3.1.tar.gz
cd libarchive-3.3.1
./configure
make
sudo make install

**Comment by erikbergsten** [comment]
I did all of this in as root and I had to exit root and re-enter to use the latest version of bsdtar, kinda dumb to get stuck on but it took me a while to figure out. It was from [this article](http://eyesfreelinux.ninja/posts/raspberry-pi-arch-and-the-fix.html) I got it.

**Comment by cprima** [comment]
Thanks for the feedback! Due to life I have not played with computers since March, but looking forward to go through this in winter.

Was there any other issue that you encountered?
Feel free to create issues, even minor.

**Comment by daymz** [comment]
If anyone gets an error on running ./configure, then please do this.  It was my case here running on Ubuntu 16.04 (I bolded the additional command)

wget https://www.libarchive.org/downloads/libarchive-3.3.1.tar.gz
tar xzf libarchive-3.3.1.tar.gz
cd libarchive-3.3.1
**./build/autogen.sh**
./configure
make
sudo make install

**Comment by teyter** [comment]
This is what I get when I try to run ./build/autogen.sh

sudo ./build/autogen.sh      2 ↵
+ aclocal -I build/autoconf
./build/autogen.sh: 58: ./build/autogen.sh: aclocal: not found

**Comment by polo16v190** [comment]
Are you on a live session?
Anyway, try to install the m4 and libtool as
sudo apt-get update
sudo apt-get install m4 libtool
It will resolve the problem I think

**Comment by teyter** [comment]
Hmm no. Installed m4 and libtool. Same error. Dunno if it's relevant but if I do it without sudo I get a completely different error:

./build/autogen.sh
/home/pi/bin/cat: 2: /home/pi/bin/cat: Syntax error: word unexpected (expecting ")")
/home/pi/bin/sed: 1: /home/pi/bin/sed: ELF��5@@HV@8: not found
/home/pi/bin/sed: 2: /home/pi/bin/sed: Syntax error: ")" unexpected
/home/pi/bin/sed: 1: /home/pi/bin/sed: ELF��5@@HV@8: not found
/home/pi/bin/cat: 2: /home/pi/bin/cat: Syntax error: word unexpected (expecting ")")
/home/pi/bin/sed: 2: /home/pi/bin/sed: Syntax error: ")" unexpected
./build/autogen.sh: 36: ./build/autogen.sh: arithmetic expression: expecting primary: "/1000000"

**Comment by polo16v190** [comment]
OK so install automake, it will remove the aclib problem :)

**Comment by cprima** [comment]
Found a great bash version check at https://stackoverflow.com/a/37939589 and added this to the bootstrap script.
Previously I used https://stackoverflow.com/a/4025065 in other scripts, but with the additional dependenc of awk the first mentioned one is really elegant.

**Comment by cprima** [comment]
Many thanks to everybody who contributed information to this issue! Greatly appreciated!

**Comment by sergey-alekseev** [comment]
There is 3.3.2 already, so an updated version:  

```
wget https://www.libarchive.org/downloads/libarchive-3.3.2.tar.gz
tar xzf libarchive-3.3.2.tar.gz
cd libarchive-3.3.2
./configure
make
sudo make install
```

**Comment by captaingoodvibes** [comment]
Running Debian Stretch v9.4
This resolved the issue for me. Just note that you have to re-login for the
`bsdtar --version`
to show v3.3.2

**Comment by SpenioPantollor** [comment]
Hello, I have a problem with make command. Make command won't work on Seagate goflex
